apiVersion:  v1

kind: ReplicationController

metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end

# Template and Replicas are direct children of the Spec Section  
spec: 
  template: 
    
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end

    spec: 
      containers:
      - name: nginx-container
        image: nginx 

  replicas: 3
  