apiVersion: v1 

kind: Service

metadata: 
  name: myapp-service

spec: 
  type: NodePort #Defines the Type of service we are creating
  ports:
    - targetPort: 80 # Optional to Provide
      port: 80 # Mandatory to Provide
      nodePort: 30008 # Optional to Provide
  selector:
    app: myapp

