apiVersion: v1

kind: Pod

metadata:
  name: worker-pod
  labels:
    name: worker-pod
    app: demo-voting-app

spec: 
  containers:
    - name: worker-app
      image: kodekloud/examplevotingapp_worker:v1 
      # Worker App has no service definition listening, hence no services are required. 

    